services:
  - type: worker
    name: telegram-userbot
    runtime: node
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    buildCommand: npm install
    startCommand: npm start
